// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqoGsE2uaW62ljNmqbUm3Z4asRrpb1gAM',
    appId: '1:585678689885:web:c23354eabce44b8ebedfb4',
    messagingSenderId: '585678689885',
    projectId: 'ilkbasarilisonuc',
    authDomain: 'ilkbasarilisonuc.firebaseapp.com',
    storageBucket: 'ilkbasarilisonuc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ErWC5fgoVbxngi6FVeTU-7PgrrkJJM4',
    appId: '1:585678689885:android:c3e9b88b5a980dbdbedfb4',
    messagingSenderId: '585678689885',
    projectId: 'ilkbasarilisonuc',
    storageBucket: 'ilkbasarilisonuc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Zjd2ifDMooMzc7fPxXb8kxnVFK7RnJg',
    appId: '1:585678689885:ios:29b5c54a9603e3cdbedfb4',
    messagingSenderId: '585678689885',
    projectId: 'ilkbasarilisonuc',
    storageBucket: 'ilkbasarilisonuc.appspot.com',
    iosClientId: '585678689885-f52etvdmjlv2rtl1edglm18p84h5inap.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeniDeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Zjd2ifDMooMzc7fPxXb8kxnVFK7RnJg',
    appId: '1:585678689885:ios:ee2ced0355d46541bedfb4',
    messagingSenderId: '585678689885',
    projectId: 'ilkbasarilisonuc',
    storageBucket: 'ilkbasarilisonuc.appspot.com',
    iosClientId: '585678689885-3apl3002pucv42a1852977oko90l3n1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeniDeneme.RunnerTests',
  );
}
